### ISSUE TITLE
Привет, думаю сможешь помочь)

### ISSUE THREAD

**Issue by jameslotte** [raritetmolodoy/tele2-profit#1]
Еще раз приветствую! Не могли бы вы мне дать свой VK/Telegram или прочую соц. сеть? Буду очень благодарен вам

**Comment by raritetmolodoy** [comment]
> Еще раз приветствую! Не могли бы вы мне дать свой VK/Telegram или прочую соц. сеть? Буду очень благодарен вам

telegram @raritetmolodoy

**Comment by ustyantsevxx** [comment]
приветствую. telegram @raritetmolodoy
