### ISSUE TITLE
Не приходит смс для авторизации.

### ISSUE THREAD

**Issue by w432w** [raritetmolodoy/tele2-profit#3]
Привет!
Только у меня приложение не работает? Смс для авторизации не приходит.

**Comment by Valtosin** [comment]
У всех. Я думаю господин @raritetmolodoy придумает что-то, в Мобильном Маркете нашли какое-то решение.

**Comment by Valtosin** [comment]
@w432w забыл сказать, что есть вариант авторизоваться вручную. 
Создаёшь в папке со скриптом файл `config.json` с таким содержанием:
```
{
	"number": "7номер",
	"token": "сюда_токен",
	"region_url": "my.tele2.ru",
	"date": "2021-12-30 12:00:00"
}
```
Токен брать из веб-версии отсюда: https://khakasia.tele2.ru/stock-exchange
Он находится в cookie-файле access_token. Но я всё ещё надеюсь, что автор починит авторизацию.

**Comment by w432w** [comment]
> @w432w забыл сказать, что есть вариант авторизоваться вручную.
> Создаёшь в папке со скриптом файл `config.json` с таким содержанием:
> 
> ```
> {
> 	"number": "7номер",
> 	"token": "сюда_токен",
> 	"region_url": "my.tele2.ru",
> 	"date": "2021-12-30 12:00:00"
> }
> ```
> 
> Токен брать из веб-версии отсюда: https://khakasia.tele2.ru/stock-exchange
> Он находится в cookie-файле access_token. Но я всё ещё надеюсь, что автор починит авторизацию.

Круто, это сработало, спасибо

**Comment by raritetmolodoy** [comment]
это и правда работает. что-то вроде универсального домена. спасибо большое за находку. сейчас подправлю скрипты и обновлю master

**Comment by ustyantsevxx** [comment]
> > @w432w забыл сказать, что есть вариант авторизоваться вручную.
> > Создаёшь в папке со скриптом файл `config.json` с таким содержанием:
> > ```
> > {
> > 	"number": "7номер",
> > 	"token": "сюда_токен",
> > 	"region_url": "my.tele2.ru",
> > 	"date": "2021-12-30 12:00:00"
> > }
> > ```
> > 
> > 
> > Токен брать из веб-версии отсюда: https://khakasia.tele2.ru/stock-exchange
> > Он находится в cookie-файле access_token. Но я всё ещё надеюсь, что автор починит авторизацию.
> 
> Круто, это сработало, спасибо
это и правда работает. что-то вроде универсального домена. спасибо большое за находку. сейчас подправлю скрипты и обновлю master

**Comment by ustyantsevxx** [comment]
залил новую версию (1.2.0)
