### ISSUE TITLE
По поводу функционала

### ISSUE THREAD

**Issue by TheKoT** [raritetmolodoy/tele2-profit#5]
Будет возможность добавлять смайлики и своё имя к лотам? И чтобы скрипт добавлял через рандомное значение времени(на всякий вдруг спалят)

**Comment by ustyantsevxx** [comment]
**приветствую.**
добавление смайликов и имени было в ранних версиях, но было выпилено с связи с тем, что это бесполезная шляпа, засоряющая кол-во доступных в сутки запросов.

**добавлять обратно не планирую**

> биржа теле2 это не авито где важна репутация продавца и прочее... тут люди заходят и покупают самый первый лот в списке (по многочисленным опросам неведующих в кодинг пользователей)

если можешь в питон, то вот то, что было раньше (вставить после выставления лота и получения его **id**):
```python
rs.patch(f'{market_api}/{lot_id}', json={
  "cost": {"amount": lot_price, "currency": "rub"},
  'showSellerName': True,
  "emojis": ["bomb", "devil", "scream"]
})
```

**Comment by Valtosin** [comment]
Полезной нагрузки от этого будет мало, а спалят ещё на стадии того, что ты быстро лоты выставляешь. 

Насчёт банов. Банят по IP-адресу, но только если ты абузишь API достаточно сильно (что возможно при некорректной работе скриптов, которыми всё ещё пытаются барыжить). Ещё также есть софт-бан за 100 перевыставлений лотов, но он снимается через сутки и является обычным делом.

Оффтоп.

**Comment by ustyantsevxx** [comment]
> Полезной нагрузки от этого будет мало, а спалят ещё на стадии того, что ты быстро лоты выставляешь.
> 
> Насчёт банов. Банят по IP-адресу, но только если ты абузишь API достаточно сильно (что возможно при некорректной работе скриптов, которыми всё ещё пытаются барыжить). Ещё также есть софт-бан за 100 перевыставлений лотов, но он снимается через сутки и является обычным делом.
> 
> Оффтоп.

в прошлых версиях была возможность выставить 100 лотов в асинхронном режиме практически одновременно, бана не было, только софт на сутки после этого; при таком подходе возникает ошибка дебетования трафика (сервер не успевает обработать или типа того), поэтому убрал - вряд ли кому надо за секунду 100 лотов поставить.

персональными банами у них никто не занимается, на всех ботов и скрипты плевать, уже сколько было дебильных фиксов с заголовками и регионами, которые обходятся даже обезьяной под сто грамм...
